### PR TITLE
Examples in README should return Promises so that Mocha waits for them to resolve

### PR DESCRIPTION
**Pull request by nikwen**
See https://mochajs.org/#working-with-promises

### CODE REVIEW

**Comment by i-like-robots** [comment]
Thanks @nikwen for taking the time for this but the current code is correct - note that the arrow function does not use curly braces but parenthesis, so the expression is returned implicitly.

**Comment by nikwen** [comment]
@i-like-robots Sorry, I totally missed that. Thank you for your fast reply. :)

**Comment by i-like-robots** [comment]
No worries, because it's such a new feature then maybe others will miss that too and I should change it 🤔

**Comment by nikwen** [comment]
I have never seen arrow functions being used with normal parentheses before, that's why it confused me. So yes, it might confuse others, too.

**Pull request closed without merging**
